# Generated by Django 2.2 on 2019-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField(verbose_name='Date Updated')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.PositiveSmallIntegerField(default=0)),
                ('code_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
