# Generated by Django 2.2 on 2019-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0002_auto_20190424_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
