# Generated by Django 2.2 on 2019-05-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0003_auto_20190429_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='Name',
        ),
    ]
