# Generated by Django 2.2 on 2019-05-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0004_auto_20190508_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employee',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='employee_name',
        ),
    ]
