# Generated by Django 2.2 on 2019-05-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0005_auto_20190508_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
    ]
