# Generated by Django 2.2 on 2019-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0006_auto_20190513_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
