# Generated by Django 2.2 on 2019-05-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0007_auto_20190515_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobimport.Jobs'),
        ),
        migrations.AddField(
            model_name='taskcodes',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobimport.Jobs'),
        ),
    ]
