# Generated by Django 2.2 on 2019-05-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0008_auto_20190516_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='jobimport.Jobs'),
        ),
        migrations.AlterField(
            model_name='taskcodes',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='jobimport.Jobs'),
        ),
    ]
