# Generated by Django 2.2 on 2019-05-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0009_auto_20190517_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id']},
        ),
        migrations.AlterModelOptions(
            name='taskcodes',
            options={'ordering': ['code_id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
