# Generated by Django 2.2 on 2019-05-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0010_auto_20190520_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='jobimport.Jobs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskcodes',
            name='job',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobimport.Jobs'),
            preserve_default=False,
        ),
    ]
