# Generated by Django 2.2 on 2019-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0011_auto_20190523_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcodes',
            name='actual_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='taskcodes',
            name='actual_footage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskcodes',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='taskcodes',
            name='footage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
