# Generated by Django 2.2 on 2019-05-30 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0012_auto_20190530_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
