# Generated by Django 2.2 on 2019-06-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0014_auto_20190604_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcodes',
            name='accumulated_budget',
        ),
        migrations.RemoveField(
            model_name='taskcodes',
            name='accumulated_footage',
        ),
        migrations.CreateModel(
            name='Accumulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_footage', models.PositiveSmallIntegerField(default=0)),
                ('acc_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('task_codes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumlator', to='jobimport.TaskCodes')),
            ],
            options={
                'ordering': ['acc_footage'],
            },
        ),
    ]
