# Generated by Django 2.2 on 2019-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0015_auto_20190606_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcodes',
            name='acc_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='taskcodes',
            name='acc_footage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
