# Generated by Django 2.2 on 2019-06-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobimport', '0016_auto_20190617_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcodes',
            name='week_of',
            field=models.DateField(auto_now=True, verbose_name='Week of'),
        ),
    ]
